export default {
  command: ['cp'],
  category: 'fun',
  isOwner: false,
  run: async (client, m, args, usedPrefix, command, text) => {
    try {
      const audioPath = './commands/CP.m4a'; // Asegúrate de que la ruta sea correcta
      await client.sendMessage(m.chat, { audio: { url: audioPath }, mimetype: 'audio/mp4' });
      m.reply('OHHH SIII 🗣️🔥 TODO COMIENZA CUANDO NO HAY NADA QUE HACER 🗣️🔥 CUANDO TODAS LAS PERSONAS SE LA JALAN VIENDO LOLIS 🗣️🔥 Y CUANDO TU TAMBIEN LO HACES 🗣️🔥 SIN IMAGINARTE QUE ALGUN DIA TODO EL MUNDO TE ODIARA 🗣️🔥 SOLO HACES LO QUE TE GUSTA 🗣️🔥 Y RESULTA QUE LO QUE HACES A LA GENTE NO LE GUSTA 🗣️🔥 INGRESAS AL EKIS VIDEOS 🗣️🔥 Y TE CREAS UNA CUENTA 🗣️🔥 TE LA PASAS VIENDO LOLIS Y AHORA ERES SUBNORMAL 🗣️🔥 MILES DE CEPE MILLONES DE LOLIS 🗣️🔥 VIENDO TU NOMBRE EN VARIOS SITIOS NOPOR 🗣️🔥 MILES DE CEPE SE HACEN MILLONES 🗣️🔥 SE VUELVEN REALIDAD MUCHAS DE TUS PAJAS 🗣️🔥LAS LOLIS SE COMPARTEN, SE DISFRUTAN, SE PASAN 🗣️🔥 SON DE LOLOS 🗣️🔥🗣️🔥EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 EL RAP DEL CPPPPPP🗣️🔥 EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 SOMOS UNA COMUNIDAD MUY GOOD🗣️🔥EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 NO ME FUNEN POR QUE SOLO ES HUMOR🗣️🔥 EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 SOMOS UNA COMUNIDAD MUY GOOD🗣️🔥EL RAP DEL CPPPPPPP🗣️🔥 MALDITA GENERACIÓN DE CRISTAL ZZZ NO ENTIENDEN NUESTROS GUSTOS GOOD🗣️🔥 NO SABEN LO QUE ES BUENO🗣️🔥SOLO SABEN VER AL VEGETA SETESIENTOS SETENTAISIETE🗣️🔥Y HABLAR DE SER SIGMAS🗣️🔥NO CRITIQUEN🗣️🔥CONSIGANSE UNA VIDA🗣️🔥MEJOR SIGAN VIENDO SUS TUTORIALES DE COMO DESCARGAR EL MINECRAFT CON TLAUNCHER🗣️🔥EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 EL RAP DEL CPPPPP🗣️🔥 EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 GENERACIÓN DE CRISTAL AJAJAJAIASA EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥 YA DEJEN DE JODER GENERACIÓN DE CRISTAL🗣️🔥EL RAP DEL CP🗣️🔥 EL RAP DEL CP🗣️🔥');
    } catch (e) {
      m.reply(`😕 Error: ${e.message}`);
    }
  },
};