export default {
  command: ['mario'],
  category: 'fun',
  run: async (client, m) => {
    const textos = [
      'Prime te quiero preñar yo sé cómo se puede hacer si estás interesado en tener huna IJO con Migo o tu me quieres preñar dímelo amor ❤️😍🍆🍑💘👬👬', // 1
      'Eres Angel hermoso Papi y quiero estar contigo amor pero en la cama desnudos y acariciarte ese culote tanrico que tienes y darle mucha verga se que tú quieres también papito lindo mándame huna foto tuya desnudo totalmente quiero ver tu cuerpo tan rico que tienes Papi', // 2
      'Se te gusta mucho Anjel te la quiero meter toda será muy rico Papi dime si quieres estar conmigo Papi te gustará mucho tenerla dentro de tu culote tanrico que tienes amor ❤️😍', // 3
      'Anjel dime de dónde eres y cuántos años tienes actualmente si quieres estar conmigo Papi pero en la cama desnudos y acariciarte ese culote tanrico que tienes y meterla toda hasta que te sientas bien culiado yo quiero con Tigo amor ❤️😍❤️🍆🍑🍆🏨🥚🏳️‍🌈🏳️‍🌈🏨', // 4
      'Mi verga 🍆 es grande y gruesa que DENTRA TODA se que tú quieras Papi hermosa mándame huna foto tuya desnudo totalmente quiero ver parada y ese culote tanrico que en cuatro para ver ese huequito abierto que quiero con Tigo Papi si tú quieres también Anjel 🍆🍑🍆😍👬🍼♨️🔥🤑👬', // 5
      'Si no te gusta mi verga no hay ningún inconveniente Papi solo tu lo decides papasito rico espero tu respuesta y arreglamos algo entre nosotros cundo tú quieras yo pago el hotel 🏨🏨 por toda la noche para estar contigo Anjel 🍆😋🤑🏨😋💸♨️ 🏳️‍🌈🇨🇴🏳️‍🌈', // 6
      'Tienes huna verga grande y gruesa me gusta mucho papito si tú quieres podemos hacerlo cuando tú quieras dime si tienes citio para hacerlo con Tigo amor estoy disponible para ti amor lindo tú lo decides papasito rico si quieres culiar con Migo amor ❤️😍❤️🍆🍑🍆🥚🍼🇨🇴🏳️‍🌈🏳️‍🌈', // 7
      'Hola Papi Alex yo quiero con Tigo Papi te quiero habrir más ese culote tanrico que tienes ya has comido muchas vergas pero te la quiero meter toda hasta que termine dentro de tu culo tan rico que tienes amor tienes 23 añitos lo quiero probar y darte duro por ese huequito abierto que tienes dime si quieres estar conmigo Papi de dónde eres y cuánto tiempo puedo estar con Tigo Papi te gusta la verga y gruesa dentro de tu culote tanrico que tienes amor espero que me escribas pronto podemos hablar bien y arreglamos algo entre mándame tu número de tu WhatsApp para agregarte y hablar con Tigo Papi es más seguro y podemos compartir fotos y videos tuyos y míos bien calientes espero tu respuesta si quieres estar conmigo Papi te quiero culiar muy rico así te DENTRE sin que te duela mucho por qué tienes ese culote tanrico bien abierto eso quiero con Tigo amor lindo 🍆🍑🍆🥰😘👬🍼🏨🥚🍼♨️🌹💐💜🏨🥚🇨🇴🏳️‍🌈🏳️‍🌈🏳️‍🌈', // 8
      'Husted es un IJUEPUTA humillativo con la gente será que tienes mucha eres hun gamin de mierda mantenido por sus moscos es hun estafador y ladrón IJUEPUTA baya comase hun cerro de mierda 💩😠😠😠', // 9
      'Me mandaron una foto de huna mujer donde le están metiendo la verga por detrás no Heras tu Sebastián OSI', // 10
      'Papito lindo tienes huos ojos muy lindos quiero ves tu cuerpo tan sexy que tienes pero desnudo para ver esa verga grande y gruesa que tienes amor lindo y ese culote tanrico que tienes amor lindo dime de dónde eres y cuántos años tienes si tienes novio o marido o estás solito yo estoy soltero y buscando un chico así de vergón como tú versátil que le gusten los hombres vergones como yo quiero con Tigo amor pero en la cama desnudos y acariciarte ese culote tanrico que tienes y esa verga te la quiero chupar bien rico asta aserte exitar mucho y que me la metas toda hasta que te vengas dentro de mi yo también haré lo mismo con Tigo amor lindo te amo mucho mi cielo espero que me escribas pronto podemos hablar bien y arreglamos algo entre nosotros te mando muchos besos en todo tu cuerpo tan sexy que tienes Papi 🥰😘🍆🍑🍆💞💘🔥🍼👬👬🏳️‍🌈🇨🇴', // 11
      'Gracias Sebastián por aserme publicidad ya me yegaron varias propuestas ya ATI no te importa para nada', // 12
      'Siga mandando fotos mías Papi gracias', // 13
      'Ya estoy en primera página gracias a ti Sebastián', // 14
      'Yo si quiero parariarme con Tigo Sebastián pero primero por la boca si tú quieres también pero sin groserías Amor ❤️', // 15
      'Yo no quiero ablar con ese marica de Sebastián culo abierto iya que dege tanta mamdera', // 16
      'Hola Sebastián más IJUEPUTA será tu puta madre maricon Doble IJUEPUTA pone culo gonorrea ya terminó la charla entre nosotros vete pa su puta mierda queda por fuera 😠😠💩💩😠😠', // 17
      'Si tú quieres lo podemos hacer José quiero huna foto tuya desnudo totalmente para ver esa linda verga grande y gruesa que tienes amor lindo te amo mucho José si tú quieres también papito rico te amo mucho espero estar contigo amor pero besos y abrazos y cuídate mucho cariño mío mándame lo que te quiero de ti papasito rico 😋 😍😋🍆🍑🍆❤️🌹🥚💋🏳️‍🌈🏨🍼', // 18
      'Solo quiero ver tu cuerpo desnudo para ver tu culo y tu verga Y gruesa que tienes amor así podemos empezar los dos si tú quieres también papito lindo mándame ya Papi te quiero culiar muy rico Papi y tu también harás lo mismo con Migo te lo prometo Sebastián si quieres así con Migo 👬🥚🌹🍆🍑🍆😘💘😍❤️🏳️‍🌈🏳️‍🌈', // 19
      'Ya se que no quieres nada conmigo Papi no tengo ninguna respuesta positiva tuya pero gracias por estar interesada en mi es todo Papi ❤️ 💋😍🔥👬 🥚 👉👌🏳️‍🌈🏳️‍🌈🏳️‍🌈', // 20
      'Si quieres jugar con tu perra hazlo pero no cuente con Migo papito los dos jugaremos pero en la cama desnudos si quieres metermela Papi pero yo ATI también quieres también papito rico 🍆😋😋', // 21
      'Si papi angel dime de dónde eres y cuántos años tienes si tienes novio o marido o estás solito yo estoy soltero y buscando un chico así de no te conozco todavía mándame huna foto tuya desnudo totalmente amor si quieres estar conmigo Papi❤️ 😍🍆🍑🍆🌹💐👬🏨🏳️‍🌈🏳️‍🌈🏳️‍🌈', // 22
      'Eso no me gusta hacerlo ya tienes el culo abierto pero si te la quisiera meter pero solo los dos mándame huna foto tuya desnudo totalmente con esa verga grande que tienes bien parada y arreglamos algo entre nosotros Angel si tú quieres así tu marido me lo como después si tú quieres también papito', // 23
      'Papi quien te dijo esa mierda son mentiras iyo quién lo hizo por no quiero hablar con ese IJUEPUTA es Sebastián Castro si tú le crees ya cosas tuya amor ❤️😍 mándame fotos y videos vien calientes los quiero ver papito rico 🍆😋👬🍼🥚💐♨️👉👌🏳️‍🌈🇨🇴', // 24
      'Cuando tú quieras Papi pero quiero estar contigo amor pero en la cama desnudos y acariciarte esa verga grande y gruesa que tienes amor lindo hasta hacerte exitar mucho para que me la metas toda y quiero que me preñes si tú quieres también papito rico te amo mucho mi cielo hermoso cuídate mucho serás todo mío iyo todo tuyo José quiero huna foto tuya desnudo totalmente pero de cuerpo entero quiero ver tu linda cara si quieres seguir con Migo José si no la mandas no confío en ti amor si quieres con Migo tengo que saber con quién estoy hablando tu me interesas mucho Papi espero tu foto desnudo totalmente de cuerpo completo te amo mi José papito rico 🍆😋🤑😋🍆🍑😋🥚🍼🍆', // 25
      'Quiero que me digas algo lo que tú quieras amor mío y quiero tu leche rica dentro de mi culo me quieres preñar yo quiero con Tigo y quiero tener hun hijo con Tigo amor lindo dime si quieres así Papi podemos estar juntos', // 26
      'Yo solo quiero verte desnudo totalmente para saber con quién boy a estar en la cama desnudos yla de tu marido también para hacer el trío será todo muy rico Papi si estás disponible para estar con Migo amor ❤️😍💐🌹🍆🍑👉👌💋🏨🍼🔥♨️🇨🇴', // 27
      'Comase hun bulto de mierda IJUEPUTA maricon te gustan las mujeres no los hombres malparido homosexual de mierda 💩😠😠😠', // 28
      'Perdón te gusta es la verga grande y gruesa dentro de tu culote tanrico que tienes', // 29
      'Está es toda tuya como te gusta Sebastián marica escudado por mujeres pero te gusta lo que te mandé te la quiero meter toda hasta hacerte sentir como todo hun Omoxesual muy definido papito rica 🍆🍑🏨🍼😋♨️👬👉👌🏳️‍🌈🏳️‍🌈', // 30
      'Ya me mandó hun mensaje ese marica de Sebastián y me dijo que solo le gustaban las mujeres por jovi los hombres maricas como tú José quieres decir con ese Omoxesual de Sebastián si quieres no quiero saber nada más que ti amor ❤️😍', // 31
      'Hola Sebastián tu heres muy infantil te gusta jugar en pendejadas yo solo quiero estar contigo amor pero en la cama desnudos y Aser el amor ❤️😍🍆🍑🍆🌹♨️👬🔥😋', // 32
      'Está es toda tuya como te gusta Sebastián marica escudado por mujeres pero te gusta lo que te mandé te la quiero meter toda hasta hacerte sentir como todo hun Omoxesual muy definido papito rica 🍆🍑🏨🍼😋♨️👬👉👌🏳️‍🌈🏳️‍🌈', // 33
      'Viejo maricon si puta madre malparido msricon infantil de mierda hasta qui llega está conversación con husted IJUEPUTA marica chao mal nacido de la mierda 😠😡🛀🖕💩💩💩💩', // 34
      'Si pero de que parte y contestame bien la pregunta que te hize paser si podemos hablar bien los dos 🥚♨️😍💘🍆🍑🍆👬🌹🏨💐🏳️‍🌈🇨🇴', // 35
      'Tan de malas que soy yo amor bueno no te preocupes será después cuando tú puedas estoy disponible para ti amor lindo te amo mucho Sebastián Jiménez te amo mucho cariño mío Besos 🥰😘💘😘🥰', // 36
      'No hemos tenido sexo los dos y ya quieres que te mandé hun celular nuevo primero tienes que metermela y preñarme después lo arreglamos algo entre nosotros te amo mucho pero bas muy rápido cariño mío Besos 🥰😘💘👅🍼🥚🥚🍼🍆🍑', // 37
      'Está muy equivocado con Migo señor yo si soy gay como tú hijo Marco Antonio el marido de Sebastián si hemos hablado con ese IJUEPUTA de Sebastián pero yo no le estoy quitando nada a nadie ese perro 🐕 es el que me busca me manda mensajes y quiere estar con Migo pero ni lo conozco en persona es hun mentiroso 🤥 habla mierda que vivía en Bogotá pero se traslado para su pueblo en Medellín no se si será cierto pero todavía me escribe lo he bloqueado en varias oportunidades pero se da la maña de comunicarse con Migo tiene un novio en el Barrio Santa Fe no digo el nombre por no me gusta meterme en problemas si ya me escribió su supuesto hijo por qué tampoco lo distingo así que me metan en problemas maricas que tenga huna excelente noche y gracias por su información 👍', // 38
      'Hola marco Antonio si Heres el novio de Sebastián Jiménez eso no me disgusta para nada el estacionamiento de mi el es el que me busca yo no tengo nada con el por es hun perro 🐕 y le gusta que le den por ese culote pero dime tú de dónde eres y cuántos años tienes me gustaría conocerte más yo Soy Mario de Colombia y vivo en Bogotá y soy gay como tú versátil me encanta la verga grande y gruesa si tú quieres podemos hablar bien y arreglamos algo entre nosotros pero si estás enamorado de ese perro 🐕 de Sebastián quédate con el Papi me gustaría conocerte más si tú quieres también yo no tengo novio ni nada con nadie por el momento si te interesa algo entre nosotros me gustaría conocerte más Papi tu lo decides mandá huna foto tuya como tú quieras espero volver a hablar con Tigo Papi cuando tú quieras ♨️😍🥚👉👌🍆🍑🍆🏨🍼🏳️‍🌈🇨🇴', // 39
      'Sabes que Papi no te conozco muy bien y estás equivocado con Migo no quiero tener nada con Tigo José si te pajeas no será por mi déjalo así Papi y gracias pero no me gusta tu tono de voz tan  vulgar con Migo no tenemos nada así que gracias y suerte con tu marido Sebastián Castro o Jiménez ❤️❤️❤️', // 40
      'Papi quien te dijo esa mierda son mentiras iyo quién lo hizo por no quiero hablar con ese IJUEPUTA es Sebastián Castro si tú le crees ya cosas tuya amor ❤️😍 mándame fotos y videos vien calientes los quiero ver papito rico 🍆😋👬🍼🥚💐♨️👉👌🏳️‍🌈🇨🇴', // 41
      'Sabes que José ya me cansé con sus MARICADAS sea más original IJUEPUTA si quieres estar conmigo dilo y no metas a los demás sea serio José ❤️👨‍❤️‍💋‍👨😠😡💩', // 42
      'Coma mucha curiosidad huevón no estamos en hotro planeta 🌎 marica y gracias por su invitación de mierda 💩💩💩💩😠', // 43
      'Dime si quieres estar conmigo Papi yo quiero con Tigo amor ❤️😍 mándame huna foto tuya desnudo totalmente pero en físico normal si quieres metermela iyo ATI te la quiero meter toda hasta que termine dentro de tu culote tanrico que tienes Papi dime si tienes citio para estar contigo amor ❤️😍 oyó pago el hotel 🏨 por toda la noche para estar contigo y hacerlo varias veces tu quieres también ♨️🍆🍑💐🥚💋👄🏨🏨👬🏳️‍🌈🏳️‍🌈', // 44
      'Quiero ser tu Amigo pero con Derechos si tú quieres también se que te gusta la verga grande y gruesa como la mía y me gusta la tuya Papi me la quieres meter de vés en cuando tú lo decides papasito rico si tienes novio el no lo Sabrá nunca tu lo decides papasito rico 😋😍🍆🍑🍆', // 45
      'Está bien Papi pero yo no te estoy Manipulando no es nesecito que seas tan vulgar si podemos ser Amigos podemos hablar cuando tú quieras solo quiero estar contigo amor pero déjalo así iya gracias por estar hablando con Migo papito 💐❤️', // 46
      'Yo soy el trompo de poner Papi manda tu y arreglamos algo entre nosotros si no quieres déjalo así no te conozco muy bien así será si quieres con Migo Papi tienes miedo de mostrarme tu cuerpo completo de pies a cabeza 🤯🗣️ si no quieres nada déjalo así no se quien eres gracias por todo lo que quiso con Migo iya', // 47
      'Goku yo te llamo por Whatsapp tengo tú número te voy agregar Papi así tengas mujer y hijos solo con Tigo amor ❤️😍😍🍆🍑💪💪', // 48
      'Gracias amor lindo te espero si QUIERO COJER BIEN RICO CON TIGO PAPITO RICO 🥚🍼😋😍🍆🍑🍆', // 49
      'No confío en ti Sebastián eres igual que ese malparido ignorante los dos son iguales pero ya me dió gusto de suspender ese grupo de Gayolos y Omoxesuales pervertidos como tú también me mandaste muchos mensajes por qué hicieras como hun marrano 🐖 igueputa tu e pediste muchas veces se equivocó con Migo Sebastián eres igual a todos los ese grupo por eso querías salirte yo si tengo dignidad y respeto con los demás tú no Papi gracias por todo lo que se te dió hay mejores que tú 🤭🤫🤫😘😡😠', // 50
      'Cuando tu quieras amor lndo estoy disponible solo para ti papito rico dime cundo y dnde lo haremos tienes sitio o yo pago el hotel para estar con tigo toda la noche y que me la metas todas las veces que tu quieras papi espero tu respuesta Amor 💕❤️😍😂', // 51
      'Amor mandame tu primero hun video masturbandose hasta ver salir toda tu leche rica que tienes Amor yo te mando tamvien pero que estes desnudo totalmente el video en ficico normal si quieres darme verga yo quiero ponerte mi culo para que me la metas toda hasta que te vengas dentro de mi culo que me lo yenes con tu leche rica papi te espero ❤️💕😍😘', // 52
      'Buenos dias Amor lindo si te guzto eda foto asi ba ser con tigo papito rico heres de Barranquilla iyo de Bogota he tenido ganas de conoser parte de la cósta esta es la oportunid para conoserte bien y co oser Barranquilla tu me bas a invitar papito lindo seria jenial para estar con tigo Amor 🥰😘💗💖👉👌💏🫂', // 53
      'Mucho Amor lindo ya quiefo tener esa linda verga grande y gruesa dentro de mi culo hasta qúe te vengas dentro de mi culo y me mo llenes con tu leche rica que tienes iyo tambien hare lo mismo con togo ALEXANDER PAPITO RICO ITU que qjieres hacer con migo dimelo Amor miio Besitos por todo eze cuerpo tan rico que me pertenese 💜💖🤩💦🇹🇷🔥🍆🍑🍆💏❣️💋🫂🏳️‍🌈🏳️‍🌈🇨🇴🇨🇴', // 54
      'Kai censt asi todabia te quiero chupar ese culito apretadito que tienes y darte lenguita por ede huquito apretado que tienes para mi verga te la quiero meter despacito sin hacerte daño cundo te dentre toda despacio te gustara mucho cuando la tengas toda dentro de tu culito tan rico que me gusta mucho papasito mio mandame huna foto desnudo en cuatro para ver ese huquito tan rico que tienes para mi besosss en ese culito rico Amor 🤩👨‍❤️‍👨🍆🍑🍆🌈🔥💕💦💗🏳️‍🌈🏳️‍🌈🇨🇴🇨🇴',
    ];

    const textoAleatorio = textos[Math.floor(Math.random() * textos.length)];
    await client.sendMessage(m.chat, { text: textoAleatorio }, { quoted: m });
  },
}